# Generated by Django 4.1.5 on 2023-02-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concerts',
            new_name='Concert',
        ),
        migrations.RenameModel(
            old_name='Musicians',
            new_name='Musician',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
